language: scala

jdk:
- oraclejdk8

scala:
- 2.10.6
- 2.11.8

sudo: false

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

after_success:
- 'sbt publish'

env:
  global:
  - secure: TbUSJJ2vPecDP76n7PAzs8MPnmSrsTRyKhcIBOE0lMARvugDJGCYBx+1z6hW7IhqnJ24P06GuX5wZ5Ma0boj+uPEMKvfnN3Qgj5xXCZhSmxCIhnXlTEUiiRM8NhSbup+ifV6tBN1UPQ6YeZ6DeliOkannPX3TWLJcxRKdVM5YUSC96NBy+MRTGPfRg9+LN+UR0nopNEBpMxE8K2t7XESm28qDwaJyP3ytGzNO2JQXtZQ2cS2jR2rcUIv/24C5zECPI6wSCOLl9E30T99hT0vWhUtezlR6AGPRe6IgvBu7KED9l9qc9jRu3bKlciwTHjk6ghw/ervf6kZYNH6+wOm4sJEkkBR1Mvz1VZU35QsP7yMxlh3IJ+68bCNdf5q9biRpNvMCxnNbBPLR1JzQh7OSWxuyp/d2aBI0oH440d5RZDGNIgFh2NjcdFakE1VwMs1bvonAJPOZJ62PBIvLOQBUjTU1oRTBpAXzBROQ6ITGYHDdAn0HdSGruFtOlqdsMryjdWoaBe4yLzjnBP2MJ843ggoY/MIAMunfFbIVqOhFYtnaN9Z4gK2DRokACQ87J40bVn1PymCYELbm4Ccr7HRUTc4N4sxifJK0bDPDB2G4bEvz8rn7usbJzFJCekABjpxFSjfCwGJ+MFN823t58LIitu/Lw63ycxUqwl0kfiRxvs=
  - secure: uU2LANlkzhNjpufcj6IKr1w1DXd7JpbLxsqyugwykS4TE81CuoSxlMln80sUC5ZnPivTycP2EsD8wXzMAkN9NsU7tTxjp1hOiom4FQ4v0HvTowyFhuM35t4c+R3bulP48+2VdS/qpvkhfMPi9RAyw6SaTxyOuSzqt/2SWRGKticSd57LImUSOUSSxiZRxLYN8qaQjd1jK4V+gm4JaLyhrOUgkhcLMkoIfQZ/mz26vc1RjZx46uDISa0ru5uDjd4ULhXzDDu+Iie/ywyfYx7fZKtIPm4SVaRVFs6CG2l7kJAOubX8c4Y2+GthlN05GIsIQo2kxsFwTg1tR1umGFqWZNaXwwUV95YCIstZJhBKP8rWyp/svB1w1S6RZHRWXlanJ5dyWDZt0iHqGelF4+Ld17Pe8Cd6QN7rXKVYYsJEaWN6H3t46q4MqboSCDG50yZ/4nTeE5qSu9UMKH6MW1/n+NTli2E1kmgHJ/PruJ0qCRe8CBJyxSaqHTecMBWe4tvls9+aCNQSEVm8La2OpLIZ5d3U3RCybTYQ1bwxe4BGZGEtA/9L2a7SP51xNHlVIqNjiMut6yt09r1vDgG1uDdAk6iQDmL/tsdCG+hlCLRZH27DZ96FCctII/XJ2EZ3ZTIXZeH6kTnUxp8VYmapMeClwswZC/LNDg0bfoJ7KKpoUHY=
