language: scala

jdk:
- oraclejdk8

sudo: false

script:
- sbt ';+test;+publish'

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

env:
  global:
    secure: "RkjtqpMWIhAjFd11A5zDBwpM7Mn2QXSzW+pVoFwivNelnR+CVkmWJe05xJjEzt71oLWLW2OFz4G9rDusREJFF/TCHhHCuFJpRjcv9+CDNfShM3r12QCnGcPYuxL8rUdZHIXacTYIr16+PHz9pPGIkxZQtlmE7IpQaOIuSgvSnpTQfE0B+ms+5rbTxklnOpM/KArHa0LHEfXsPaHkqX668jwa3sQZYoPgYT7wmxf2+ZhchKyGwsPz/34lJCNSffk5F8B8OnVkct1pTPWtGGkrb3UynOomhzoufLON9Gt/V+Io8ZSu5KbQJ3jedapUCKg0v9vGafBrghCHbB0TSC2B4xVN6EQ/cBlx703SwnGauC3kFS7xT8QiSFIr350ywkDbQvt5a3uQh64l5dk0RiENkcJOFBkLz3cYW9egfuNQe45ibBLaQkweMHvAFxIJiDeO2LEdpPjoID0C/pVZVivGJxLbnD77jnS3HvGuZhiPcXIoKdSxjyJ72Ufex9Xk1hq0IBmOnNMnXGM2cfABOEIl4J0tEgOF1ItkxTQIitHaFgPgIpX8QUbE4NgwqDWOK5cnSjfT7vAVMmRaiHgREBFZnC2wj3/fd/3xwZ8S0wSRQWV5ECqb2Z7DT+6qRkETZKdR/6cCRlc2P0QwTRtvUgKoGQLzweAnFBbId5WD91zxHAY="
    secure: "MN3RI9pBVfZaMnj1OmS7+lwryq4YTf4/tyy2Gh/PAjF/B7qfVyHZ59Wn93eU7VmZYZ1YCrg2aHlGD8Tg3nXmlEyZanvJNsuzPYwfl0COrst3D00ndudGIxTpQE3vPIwlpMC41liCcLXU4t9ODjY8SLM3Xd9VAxsE9pu5l8YzMpbgnT5SH4cjBxMcs8mJ4mBqWF6NNbmAWE9bNH70q0ppXea9F90TDQTErq4icCCbjUJ2lkfKvCPF+sAlrrIcMBcewR+dmO4kGBJ36taKnZVXNwWy/td/XZDO0EjMYbTaw5g/VK98Qepr6r6qsUifZuB1lzzbPkg7IP/KGdyLIJVed6Jx9yMnWzorGGvboQaxNgTCAa/fJF+otAkW2+hmEkaO3chu4C/ItsDDpk0CoaqgI6eM7jPudJ93txOE26x7PvilDo/MvV3G/0qIfg9Hzeor1gBvFUNBwZSPoxB/ZQoMZcRcc+KppDm672Cgmp6O1BLMC2c7XAgeKabMCYlJU7hYGI0eEECsnGzvU/Ws/pf22H2pTNQsSuZs/rK6ZVtwyhEGIy7dTkxnmIrTbv4EDTVCnp3bEHETsSVJoujvz5X2SlCZOgNvgUoBTHpHwTFGj5rZLJDDFwZqiRW/mA7f0JxIZSSV1zYGVnipLeo9ibEUqic1wgvThQBFKbBIK/Ii8Ao="

