language: scala

jdk:
- oraclejdk8

sudo: false

script:
- sbt +test

after_success:
- sbt +publish

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

env:
  global:
  - secure: "TyHxawrOLpLgcPZjj2RXgx+5Yev/QHbqLv8UYt1MFh3iZiYeCkZb1kEF0KL+5A0NYbdGNGvFnmh1VoIv0hjXE81r9dAwR0ykTzde+f1mg0DBg03X8IjyrdyeOJKuMwhStf9x4Fl+7eQr3OauOUnKSjl1onkRxBGF2LFKiyLPlsbYCD/WJ8oGUPjiANGWQY6xeJxVknKKyqfaUnBlJ0K51qevd/cjf2G/j6zf3IEkV0/9A2zdmcj57+PI6VJ8QinnOEVCY5I1sBdhxVj1m4oEiGDJdH6XW6nAK4apwKl6fRsF+pHtxfEiF93L6C/bXY/2wBEUoRzLHQkU6P5XU7o9ho1HiZP5A0IDXYbJkhDnwP3dGI+lRUZBgy4TGOYqCbcMagt1YJ1D2UDLHYoFI2XEvgR6ch77skoqj9fdCW6nKSI8HqHsTSxQuEZZvPV7vfSx5DMvHN8w1+0fg0kzXSLbOdbV/SJ9gcdYaC0RbsGLdkUaohW0FxXCKfphwwHBQfGyap1jvmNjauEkZVoLEkC6ixZOo7IoKNhvT+Pf61sm3gB5/gt2sEd8RkNBAcw5oS8EXc4t9LUEpVFLZH67qJMSz3PmbUdBYKZWK6oNuPAK3LYfOn25tjdWxo4AOucuTUULhAVml2bhhHF6Sic6S2U1iZOnnEyaxq2Pwf07Fl4Qsvg="
  - secure: "J6ifkzl4x8jm+sc6+QNxoxNHPmnC++Xb4B6CuAOngFDlCrRLYyYudWhS/B7gaIjK1G2qRh6zf+1D4ux3imZTV7WulTqFi0QMcsP7Uzr1PPlziS/GmqA/cTZ14Xi7ctVK96HlO8aasRoAaDJIdqt4tGbVUOa/vHS4zVgmfOro3b1KOIGb3gTX+I+sHz2s8MNvTY1eQrYMVE03U7TEMJM3ShIDYgBOFIQzfHsOxrXnZ29f5jLK5A58tttiPf5X1ryrNyDOGlG9j9K3fhFbW2s6B5MUk5aiKi9rIakgsym2R4wVCKVQaCVCWWVGTN6nAiI9ewmOwlCktwU4dj22rqNTY1nrZPst1ww1/+0kPT1LIUR844GyFMNb7L+9FpBn3/026ufxMzhp/zCvHmNmKUYlSJ/DeHQSGeBlhSoq1f38Uc53L9tpooKN9ySmhJl18339gxIOyQgwtnXFgSoEj0JJIWWXZ7CF7p4Osa1qijOG41CHqdhsDN6rW/dx1/deqtRy4yY+rDbpjISiPSE36Hb+wgFhKCbMGsK0CkLlT0IuEnM4ZzOX6BMj+/zM47kzxEhMvpnWl3vuSuhHOvBAWJeJZEjFee666dwAXvEOGq0niTpTG/UkpnG3rQDaXN9HPAUHMxdKZjEWAxDA/vPoPansyr4TTr6Om9N6WefPbiF8DA4="
